[workspace]
members = [
    "polybius",
    "keyboards/planck",
    # "keyboards/viterbi",
    "tests/nonblocking_i2c",
]

[profile.dev]
opt-level = "s"
lto = true

[profile.release]
opt-level = "s"
lto = true