[build]
target = "avr-atmega32u4.json"
rustflags = [
    # Workaround for running into rust-lang/rust#83972
    "-Csymbol-mangling-version=v0",
]

[target.'cfg(target_arch = "avr")']
runner = ["ravedude", "leonardo"]

[unstable]
build-std = ["core"]
build-std-features = ["compiler-builtins-mangled-names"]
